sonar.organization=nhsdigital
sonar.projectKey=NHSDigital_eps-common-workflows
sonar.host.url=https://sonarcloud.io

sonar.coverage.exclusions=\
    release.config.cjs, \
    scripts/trigger_release.py, \
    packages/semantic_release_jira/index.js
