name: PR Title Check

on:
    workflow_call:

permissions: {}
jobs:
    pr_title_format_check:
        runs-on: ubuntu-22.04
        permissions:
            pull-requests: write
        steps:
            - name: Check PR Title is Prefixed with Change Type
              id: check_prefix
              continue-on-error: true
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  if [[ "$PR_TITLE" =~ ^(Fix|Update|New|Breaking|Docs|Build|Upgrade|Chore):.*$ ]]; then
                    echo "PR title is prefixed with change type."
                  else
                    echo "PR title is not prefixed with change type."
                    exit 1
                  fi

            - name: Check PR Title contains Ticket/Dependabot Reference
              id: check_ticket_reference
              continue-on-error: true
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  if [[ "$PR_TITLE" =~ ^.*:.*\[([A-Z]+-[0-9]+|dependabot)\].*-.*$ ]]; then
                    echo "PR title contains ticket or dependabot reference."
                  else
                    echo "PR title does not contain ticket or dependabot reference."
                    exit 1
                  fi

            - name: Extract Ticket Reference
              id: extract_ticket_reference
              if: steps.check_ticket_reference.outcome == 'success'
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  if [[ "$PR_TITLE" =~ ^.*:.*\[([A-Z]+-[0-9]+|dependabot)\].*-.*$ ]]; then
                    TICKET_REF="${BASH_REMATCH[1]}"
                    echo "Extracted ticket reference: $TICKET_REF"
                    echo "TICKET_REF=$TICKET_REF" > "$GITHUB_OUTPUT"
                  else
                    echo "No ticket reference found."
                    exit 1
                  fi

            - name: Fail job due to invalid PR title format
              if: steps.check_prefix.outcome != 'success' || steps.check_ticket_reference.outcome != 'success'
              run: |
                  echo "Job failed due to invalid PR title format."
                  exit 1
