name: Scheduled Update Devcontainer Version

on:
    workflow_dispatch:
    schedule:
        - cron: "0 18 * * 4"

jobs:
    update_devcontainer_version:
        uses: ./.github/workflows/update-dev-container-version.yml
        permissions:
            contents: read
            packages: read
            pull-requests: write
        with:
            base_branch: main
        secrets:
            CREATE_PULL_REQUEST_APP_ID: ${{ secrets.CREATE_PULL_REQUEST_APP_ID }}
            CREATE_PULL_REQUEST_PEM: ${{ secrets.CREATE_PULL_REQUEST_PEM }}
